#!/usr/bin/env bash
# Bash script that displays:

# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed
for file in *; do
    # Check if the file is not a hidden file and not a .md or .pub file
    if [ ! -f "$file" ] || [[ "$file" == .* || "$file" == *.md || "$file" == *.pub ]]; then
        continue
    fi
    if [[ "$file" == *-* ]]; then
        name_after_dash=$(echo "$file" | cut -d '-' -f 2-)
        echo "$name_after_dash"
    fi
done