#!/usr/bin/env bash
# A script to change localhost addresses

# Backup the original hosts file
cp /etc/hosts /etc/hosts.bak

# Add an entry to redirect localhost to 127.0.0.2 and facebook.com to 8.8.8.8
echo "127.0.0.2	localhost" > /etc/hosts
echo "8.8.8.8	facebook.com" >> /etc/hosts
