#!/usr/bin/env bash
# A script to change localhost addresses

# Backup the original hosts file
cp /etc/hosts /etc/hosts.bak

# Add an entry to redirect localhost to 127.0.0.2 and facebook.com to 8.8.8.8
cp /etc/hosts ~/hosts.new
echo "127.0.0.2 localhost" > ~/hosts.new
echo "8.8.8.8  facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts